#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../" >/dev/null && pwd)"

source $PROJECT_ROOT/tooling/app-bundle/common/generate-apks.sh
source $PROJECT_ROOT/tooling/app-bundle/common/install.sh

BUILD_TOOL=${1:-"buck"}

rm -rf $PROJECT_ROOT/.tmp
mkdir $PROJECT_ROOT/.tmp

# Setting default paths
APKS_PATH="$PROJECT_ROOT/.tmp/app.apks"
BUNDLE_PATH=""

if [ $BUILD_TOOL = "gradle" ]; then
  BUNDLE_PATH="$PROJECT_ROOT/app/build/outputs/bundle/debug/app.aab"
else
  BUNDLE_PATH="$PROJECT_ROOT/buck-out/gen/app/bundle_debug.apk"
fi

$PROJECT_ROOT/tooling/app-bundle/$BUILD_TOOL/build-app-bundle.sh
generate_apks $BUNDLE_PATH $APKS_PATH
install_apks $APKS_PATH