#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../" >/dev/null && pwd)"

source $PROJECT_ROOT/tooling/app-bundle/bundletool/bundletool.sh

BUILD_TOOL=${1:-"buck"}

# Setting default paths

DEVICE_SPEC_PATH="$PROJECT_ROOT/results/motog_5s_plus.json"

BUNDLE_PATH="$PROJECT_ROOT/buck-out/gen/app/bundle_debug.aab"
APKS_PATH="$PROJECT_ROOT/buck-out/gen/app/bundle_debug.apks"
DEVICE_SPEC_PATH="$PROJECT_ROOT/tooling/app-bundle/specs/emulator_google_pixel_2.json"
DEVICE_APKS_DIR="$PROJECT_ROOT/buck-out/gen/app"

rm $APKS_PATH || true

$PROJECT_ROOT/tooling/app-bundle/$BUILD_TOOL/build-app-bundle.sh
generate_apks $BUNDLE_PATH $APKS_PATH
# get_device_spec $DEVICE_SPEC_PATH
extract_apks $APKS_PATH $DEVICE_SPEC_PATH $DEVICE_APKS_DIR
# install_apks $APKS_PATH

